# Generated by Django 2.2.6 on 2019-11-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_int', models.BigIntegerField(max_length=512)),
                ('binary', models.BinaryField(max_length=512)),
                ('char', models.CharField(max_length=512)),
                ('date', models.DateField(max_length=512)),
                ('date_time', models.DateTimeField(max_length=512)),
                ('decimal', models.DecimalField(decimal_places=2, max_digits=9)),
                ('duration', models.DurationField(max_length=512)),
                ('email', models.EmailField(max_length=512)),
                ('file', models.FileField(storage='C:/Users/dLnnnnnn/Desktop/1.txt', upload_to='')),
                ('file_path', models.FilePathField()),
                ('float_field', models.FloatField(max_length=512)),
                ('image', models.ImageField(upload_to='')),
                ('integer', models.IntegerField(max_length=512)),
                ('generic_ip', models.GenericIPAddressField()),
                ('null', models.NullBooleanField()),
                ('positive_integer', models.PositiveIntegerField(max_length=512)),
                ('positive_small_integer', models.PositiveSmallIntegerField(max_length=512)),
                ('slug', models.SlugField(max_length=512)),
                ('small_integer', models.SmallIntegerField(max_length=512)),
                ('text', models.TextField(max_length=1024)),
                ('time', models.TextField(max_length=512)),
                ('URL', models.URLField(max_length=256)),
                ('UUID', models.UUIDField()),
            ],
        ),
    ]
